export const ITEMS_REQUEST = 'SEARCH_SKILLS_REQUEST';
export const ITEMS_REQUEST_FAILURE = 'SEARCH_SKILLS_FAILURE';
export const ITEMS_REQUEST_SUCCESS = 'SEARCH_SKILLS_SUCCESS';
export const DETAILS_REQUEST = 'SEARCH_SKILLS_REQUEST';
export const DETAILS_REQUEST_FAILURE = 'SEARCH_SKILLS_FAILURE';
export const DETAILS_REQUEST_SUCCESS = 'SEARCH_SKILLS_SUCCESS';